# Generated by Django 5.2 on 2026-02-16

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Enable pgvector extension
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name="ContentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("era", "Era"),
                            ("topic", "Topic"),
                            ("tradition", "Tradition"),
                            ("person", "Person"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
            ],
            options={
                "ordering": ["tag_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("youtube_channel", "YouTube Channel"),
                            ("youtube_playlist", "YouTube Playlist"),
                            ("blog", "Blog"),
                            ("website", "Website"),
                            ("book", "Book"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "scrape_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Source-specific configuration",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("transcript", "Transcript"),
                            ("article", "Article"),
                            ("book_chapter", "Book Chapter"),
                            ("lecture_notes", "Lecture Notes"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External identifier (e.g., YouTube video ID)",
                        max_length=255,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("raw_text", models.TextField()),
                (
                    "processed_text",
                    models.TextField(blank=True, help_text="Cleaned and normalized text"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (duration, views, etc.)",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Whether chunks have been generated"
                    ),
                ),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence score for auto-tagged content (0.0-1.0)",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentitem",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contenttag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                through="content.ContentItemTag",
                to="content.contenttag",
            ),
        ),
        migrations.CreateModel(
            name="ContentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.VectorField(dimensions=384),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Chunk-level metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "ordering": ["content_item", "chunk_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="contenttag",
            constraint=models.UniqueConstraint(
                fields=("name", "tag_type"), name="content_contenttag_name_tag_type_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentitemtag",
            constraint=models.UniqueConstraint(
                fields=("content_item", "tag"),
                name="content_contentitemtag_content_item_tag_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="content_contentitem_source_external_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["-created_at"], name="content_con_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["source", "content_type"], name="content_con_source__idx"
            ),
        ),
        # Add HNSW index for vector similarity search
        migrations.RunSQL(
            sql=(
                "CREATE INDEX chunk_embedding_hnsw_idx ON content_contentchunk "
                "USING hnsw (embedding vector_cosine_ops) "
                "WITH (m = 16, ef_construction = 64);"
            ),
            reverse_sql="DROP INDEX IF EXISTS chunk_embedding_hnsw_idx;",
        ),
    ]
