# Generated by Django 5.2 on 2026-02-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("start_year", models.IntegerField()),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True, help_text="Null for 'present'", null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Short summary for cards"),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code (e.g., #C2410C)", max_length=7
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "start_year"],
            },
        ),
        migrations.CreateModel(
            name="KeyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "era",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_events",
                        to="eras.era",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "year"],
            },
        ),
        migrations.CreateModel(
            name="KeyFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Bishop of Hippo'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "era",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_figures",
                        to="eras.era",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "birth_year"],
            },
        ),
    ]
